### ISSUE TITLE
Domain of website expired!

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#110]
Need to renew domain of website and cannot open website. Instead, seeing something like this page: 
<img width="1093" alt="image" src="https://github.com/QC-UCI/qc-uci.club/assets/69136009/fbb52235-9ba9-469e-9c6a-94fdb8bfde9d">
@omarcostahamido and @jcwang111 Can you help with this issue please?

**Comment by omarcostahamido** [comment]
I bought it originally and paid it out of my pocket for a couple of years, but then passed it along to @Chriscrosser3310 I don't know more than that, but at least the current president should know.

**Comment by dssikdar** [comment]
How did you buy it? Do you have any advice on the process so that I can buy the domain?

**Comment by Chriscrosser3310** [comment]
> 

Hi @dssikdar, yes it expired two days ago; I have just renewed it. Could you let me know your email and I'll transfer it to you?

**Comment by dssikdar** [comment]
Oh, thank you so much! Yes, my email is: dssikdar@gmail.com

**Comment by Chriscrosser3310** [comment]
> Oh, thank you so much! Yes, my email is: [dssikdar@gmail.com](mailto:dssikdar@gmail.com)

Great, thanks! You should have received an email from Namecheap.

**Comment by dssikdar** [comment]
Yes, I did! Thank you. It's all set! 

Just putting the link for reference in the future: https://ap.www.namecheap.com/Domains/DomainControlPanel/qc-uci.club/domain/
