### ISSUE TITLE
Header covers background image depending on screen size 

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#116]
In a desktop, with normal zoom, website looks good, header and background image have no overlap. But in other cases, esp in mobile view, they overlap - header covers some or all of background image. 

![image](https://github.com/QC-UCI/qc-uci.club/assets/69136009/f6792308-3921-4a82-92fd-ec0fe33d67a8)
![image](https://github.com/QC-UCI/qc-uci.club/assets/69136009/6035b126-9a65-4d97-ad1f-e3fdd73daca5)

**Comment by omarcostahamido** [comment]
hey @dssikdar if you want to ask for my help, then ask for my help. Don't just assign an issue to me. That'd simple courtesy. I mean I'm not even listed in the current team/advisor list, so I am technically not working for it.
That being said, I'm happy to take a look at it. And I'm happy to see the club progressing.
Let's see now...

**Comment by omarcostahamido** [comment]
Ok, here are 2 possible (and somewhat complementary) solutions.
Please see the linked PRs.

**Comment by dssikdar** [comment]
Yes, I am sorry @omarcostahamido -- I should have requested your help. And very much thanks for helping. I will take a look at the PRs asap.

**Comment by dssikdar** [comment]
Since I like Header Solution 1 #117 better, I'll go with it. Thank you very much for helping out.

**Comment by omarcostahamido** [comment]
Sure, go ahead and merge the one you prefer. It will auto close this issue.
