### ISSUE TITLE
height of slideshow is very elongated in mobile view

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#119]
Like the title indicates, on a phone, if you open the website, the slideshow pictures appear quite skewed. Since it's on the home page, it looks awkward. 

@omarcostahamido Could you please take a look at this issue if you have time? Thank you. 

@KrishnaV04 and @amhaiskar0921 It would be greatly appreciated if you guys can help resolve this issue. I tried to, but I couldn't. Thanks.

**Comment by omarcostahamido** [comment]
☝️ there

**Comment by dssikdar** [comment]
Thank you so much. I also like the way you did it.
