### ISSUE TITLE
overall styling

### ISSUE THREAD

**Issue by Chriscrosser3310** [QC-UCI/qc-uci.club#13]
I'm neither familiar with web dev nor CSS/HTML, but I‘ll provide a few personal thoughts on the overall styling:

1. The white square canvas (not sure if I call it right) behind the titles on each page doesn't look very good. For example, this is the one on the "Events" page: 
![image](https://user-images.githubusercontent.com/31495624/93032783-2cbca600-f5e8-11ea-9868-8d9a8435732b.png)
The other two in the "Team" and "Join" page also have the same style for now. I think we can remove the canvas, or maybe we can change the corners to be round, like the one we have for members:
![image](https://user-images.githubusercontent.com/31495624/93032989-28dd5380-f5e9-11ea-9c75-5dced03d9bfb.png)
In fact, I don't think titles are even necessary, so we can remove it if you guys agree.

2. I personally think the initial design for the "Team" page looks better than the current version (except for the last point I made, for which I propose to remove the title or set the squares' corners to be round), and I think we can stick to this style across other pages too, including Events, Join and so on. This is the initial design:
![image](https://user-images.githubusercontent.com/31495624/93033057-66da7780-f5e9-11ea-97cb-93f077bb5713.png)
That is, we can have the top bar in some dark color while having the main page's background in a lighter color. An example of this style is qcb's website: https://qcb.berkeley.edu/team.shtml. Screenshot:
![image](https://user-images.githubusercontent.com/31495624/93033282-77d7b880-f5ea-11ea-8d1d-d303b4ab806a.png)

What do you guys think?

**Comment by andyyPark** [comment]
The title boxes should be rounded and it appears that I was using the variable without first declaring it haha. For your 2nd point, I personally like the initial background color as well. It would be great if we can have more inputs on this.

**Comment by andyyPark** [comment]
The border-radius is fixed (refer to #12 )

**Comment by omarcostahamido** [comment]
```
It would be great if we can have more inputs on this.
```
I don't have strong preference for those two items, so if you decide on light background and round corners, that is perfect for me. 
Also, you don't have to wait on every board member's input - it's proven that it won't happen in useful time.
If someone strongly disagrees with the way something looks they can chime in, and we can always dealt with it and make necessary changes it in the future.
I said it before: we just really need to have something out.
thanks

**Comment by TDHTTTT** [comment]
If @andyyPark finds design a little bit hard, some css/frontend framework might help. I have heard [tailwind](https://tailwindcss.com/) is pretty minimal and good, which should be pretty easy to integrate into our current code. Another popular framework is React. I have used React which takes some time to set up and learn but it is more powerful and has more resources. Basically these frameworks make design easier as it is incredibly easy to re-use the "good-looking" components that people already built. Anyways, I like our minimal approach a lot (since we know exactly everything that is happening) and if we can keep it this way, that's great.

**Comment by omarcostahamido** [comment]
Those options require setting up a deployment system*. They don't just work on plain html+js+css. AFAIK
If @andyyPark is at ease with that, then by all means, I can learn just enough to be able to work with that.

* meaning you need to build the static documents every time you make a change. Maybe there is a way to create an automation in github to do that itself, but at I am not at there yet.

**Comment by andyyPark** [comment]
I'm not too experienced with other frontend frameworks other than html/css/js haha.. Maybe we can have everything in plain html for now and maybe implement react after?

**Comment by omarcostahamido** [comment]
then let's drop that idea.

I'm closing the issue now, since we are also starting to deviate from OP.
If @Chriscrosser3310 or anyone else feels we should still discuss this, you can reopen it, np.

thx

**Comment by omarcostahamido** [comment]
I know I closed this issue already, but if anyone is still following it, and is interested in some of what we were discussing:
https://nextjs.org/conf
