### ISSUE TITLE
Improve contact form css

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#18]
Following @DanielQ56 [here](https://github.com/QC-UCI/QC-UCI.github.io/pull/14#issuecomment-695157764),
The contact form can have "more specialized css".

**Comment by andyyPark** [comment]
@all-contributors please add @DanielQ56 for code

**Comment by omarcostahamido** [comment]
also, please see #45

**Comment by omarcostahamido** [comment]
Heads up @DanielQ56 .
@TDHTTTT has worked on this here #48

**Comment by andyyPark** [comment]
This was fixed by #48
