### ISSUE TITLE
add Footer

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#19]
Since you listed it on the [readme](github.com/QC-UCI/QC-UCI.github.io), add a footer saying:
© 2020 QC@UCI

and maybe link it to the contact page?

**Comment by Prateeknandle** [comment]
hey! I want to work on it...

**Comment by omarcostahamido** [comment]
Here you go. Looking forward to seeing your PR :)

**Comment by andyyPark** [comment]
@all-contributors please add @Prateeknandle for code

**Comment by omarcostahamido** [comment]
@andyyPark @Prateeknandle 
This issue should not have been closed.
And #29  should have not been merged as it is not ready.
- The footer didn't follow a consistent style with the rest of the website
- it didn't follow the instructions on this issue to create a hyperlink to the contacts page.
- It only appears on one page...

Please @andyyPark next time, request contributors to make changes before merging.

@Prateeknandle @andyyPark please fix it and only then close this issue.

**Comment by andyyPark** [comment]
this was fixed by #44
