### ISSUE TITLE
add slogan and club description

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#21]
title says it all, there has been a notion task about this for a while too.

**Comment by andyyPark** [comment]
Hey @omarcostahamido my apologies I was slow with this website for this and last week. I have a paper coming out soon and I was focusing on that. I will try to get the website up before the virtual involvement fair!

**Comment by omarcostahamido** [comment]
@andyyPark good luck on the paper, and thanks for looking into this soon!

**Comment by omarcostahamido** [comment]
just an idea: for starters, this could replace the temporary text on the current readme.md.

**Comment by andyyPark** [comment]
Will this slogan go on our website?

**Comment by omarcostahamido** [comment]
that's the idea.

**Comment by omarcostahamido** [comment]
@dssikdar where exactly was it completed?
It is usually a bad idea to just close things manually as completed without any further reference or explanation... It defeats the purpose of an issue tracker.

**Comment by dssikdar** [comment]
The club description is in the "about us" section. For the slogan, I was thinking of not putting any because I don't want to cluster it too much. 

Also, sorry again for closing the issue without comment.

**Comment by omarcostahamido** [comment]
Ok. So, close this issue as `will not fix`.

For the reference, imagine that you did complete this but you forgot to add the comment on the push commit message. You could still reference/link to the commit just by pasting its github url or hash here, like: https://github.com/QC-UCI/qc-uci.club/commit/6371b2ba8ea059b63cdb6fc517e056e16e3c7a25

Best,
OCH

**Comment by dssikdar** [comment]
ok
