### ISSUE TITLE
tag president on team page

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#24]
add additional tag to mention who the president is, on current and previous board.
I thought this would be important.

**Comment by pranavvp10** [comment]
Hi @omarcostahamido  can I add this ? where can I get the info about that?

**Comment by omarcostahamido** [comment]
current President is Chris Chen, previous president is Tony Tong.

**Comment by omarcostahamido** [comment]
there you go.
Looking forward to see your PR.

**Comment by pranavvp10** [comment]
Thanks for info . working on it
