### ISSUE TITLE
add small description to each team

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#25]
something that was on notion already and wasn't included on this first merge.

**Comment by omarcostahamido** [comment]
copying it here.

current:
Despite the pandemic, and the several constrains associated with that, QC@UCI is facing the new academic with renewed energy and a new team. Check out how to [join us](http://www.qc-uci.club/join), and head to our [event page](http://www.qc-uci.club/event).

previous:
QC@UCI first became an official UCI club during Fall 2019. The first open meeting took place in November 15. Several open meetings followed, being lead by both board and club members.

founding:
The idea of QC@UCI was born in the Summer of 2019 when Tony Tong and Omar Costa Hamido met in Switzerland at the _Quantum Information for Developers_ summer school at ETH, Zürich.

**Comment by andyyPark** [comment]
I just added to the master @omarcostahamido!

**Comment by omarcostahamido** [comment]
thank you @andyyPark .
and congrats for commit number 💯 ! 🎉

Just recently I've seen a comment from @Ahmad-Fermion on notion mentioning that the description of founding team is not complete.
I'd like to invite @Ahmad-Fermion  to proposed a change to that text.

we can then close this issue.

Thanks

**Comment by Ahmad-Fermion** [comment]
@omarcostahamido I was in touch with Tony. It is fine with me now. My discussions with Tony started on Reddit and it continued.

**Comment by omarcostahamido** [comment]
ok, thx.
