### ISSUE TITLE
fix teams contacts

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#26]
Ahmad and Keira's contacts on team page are blank.

**Comment by omarcostahamido** [comment]
Ahmad
  [linkedin] https://www.linkedin.com/in/ahmadreza-rajabi 
  [email] mailto:arajabis@uci.edu
Keira
  no contacts (so remove the icons)

**Comment by andyyPark** [comment]
Just fixed this! Please check and let me know if I'm missing something

**Comment by omarcostahamido** [comment]
thanks @andyyPark !
