### ISSUE TITLE
Recognize the contributions of members?

### ISSUE THREAD

**Issue by andyyPark** [QC-UCI/qc-uci.club#27]
Although this project is relatively simple, I was thinking of adding a section in our REAEDME to recognize all the contributors. Here is an idea: [https://github.com/all-contributors/all-contributors](url)

**Comment by omarcostahamido** [comment]
duplicate of #22 right?

also the url. somehow is hyperlinked to https://github.com/QC-UCI/QC-UCI.github.io/issues/url

**Comment by andyyPark** [comment]
Oops you are right let me close this one

**Comment by omarcostahamido** [comment]
if anything this means that we are thinking alike. 
which is a good sign!
