### ISSUE TITLE
a cool domain name

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#4]
Following what @TDHTTTT said [here](https://www.notion.so/a-cool-domain-name-963502e584694ccca99ff56e2f40f222?d=f26475e2-8b2e-4adf-a7ab-e92311d150a7#c30e99f91df94928b6b8e716dae7e160), a cool domain like qc.uci.edu might be hard to get. right now it is qc-uci.github.io.
something in the middle might be possible.

**Comment by omarcostahamido** [comment]
i just acquired qc-uci.club ⭐

**Comment by andyyPark** [comment]
nice!

**Comment by omarcostahamido** [comment]
Done: http://www.qc-uci.club/
💯

**Comment by omarcostahamido** [comment]
Done: http://www.qc-uci.club/
💯
