### ISSUE TITLE
embed new qc@uci UCI-Virtual Booth video

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#41]
https://www.youtube.com/watch?time_continue=3&v=1s9clhbkHk4&feature=emb_logo

@andyyPark need to think where we can add this. I was thinking in either index or join page.
Last case scenario just as an added link for UCI VB event.

**Comment by Chriscrosser3310** [comment]
I would say adding it to the home (index) page makes more sense. eg. Duke's QC org has its info session on its homepage: http://duqis.org/

**Comment by omarcostahamido** [comment]
thx. we'll do that.

now... who would like to work on this...?

**Comment by andyyPark** [comment]
Please check #54!

**Comment by omarcostahamido** [comment]
☝️ 
@andyyPark YES
so satisfactory :)
