### ISSUE TITLE
no president tag on founding team

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#43]
The founding team doesn't need to have the president tag.

Hi @pranavvp10 ,
Here is a good follow up to your contribution, if you'd like to tackle it.
What is an elegant fix you can come up with?
Would you like me to assign this to you?

**Comment by pranavvp10** [comment]
Hi @omarcostahamido  the founding team also need President tag? Or I accidentally assigned president tag on founding members too.?

Oh I understand. This happens because the former president have both prev and founding data ids. We may have to make it seperate? The prev and founding.

**Comment by omarcostahamido** [comment]
The easiest way would be to just duplicate tony's profile with different IDs, but then when we update the bio and other information we would need to do it twice. So, this is the challenge: can you think of a way to hide the president tag if it is on founding members list?
Can I assign this to you @pranavvp10 ?
:)

**Comment by andyyPark** [comment]
@pranavvp10 This can be done using some javascript!

**Comment by pranavvp10** [comment]
hi  @omarcostahamido  @andyyPark  I have solved the issue  but I had to use jQuery(4 lines of JQuery). will it create a problem? can I push the changes?

**Comment by omarcostahamido** [comment]
@pranavvp10 please don't use jquery.
We'd like to keep this project plain vanilla html+js+css.
Thank you.

**Comment by pranavvp10** [comment]
@omarcostahamido  I have removed it using Javascript. Please review the PR . #46 . Thanks

**Comment by omarcostahamido** [comment]
somehow this doesn't work anymore.
I know of a fix though.
