### ISSUE TITLE
weird artifacts on contact form

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#45]
i'm seeing this on the contact form:
<img width="1142" alt="Screen Shot 2020-09-28 at 6 25 38 PM" src="https://user-images.githubusercontent.com/18335360/94502043-1b62c480-01b8-11eb-8998-7f826dfbe9a2.png">

needs to be fixed.

**Comment by omarcostahamido** [comment]
@DanielQ56 would you like to take a look at this?

Also, looking forward to #18 !

**Comment by TDHTTTT** [comment]
Hey I have re-done the form at https://github.com/QC-UCI/QC-UCI.github.io/pull/48

**Comment by omarcostahamido** [comment]
thank you @TDHTTTT

**Comment by andyyPark** [comment]
This was fixed by #48
