### ISSUE TITLE
documentation in readme about Tailwind

### ISSUE THREAD

**Issue by TDHTTTT** [QC-UCI/qc-uci.club#53]
Just realized I need to provide some setup info in readme. I am working on it.

**Comment by omarcostahamido** [comment]
this one is very clear from OP. 
But please make use of the assignees feature.
It's the best way to avoid people accidentally working on the same thing.

**Comment by omarcostahamido** [comment]
this was closed by #55

**Comment by TDHTTTT** [comment]
Sorry I noticed that my explanation is not clear. Most importantly one needs to execute `npm run build` when `css/style.css` is tweaked.
