### ISSUE TITLE
Rename repo to qc-uci.club

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#58]
Since we no longer are accessing it via qc-uci.github.io, it would make it more meaningful/easy to identify if it is named qc-uci.club

@andyyPark 
@TDHTTTT 
@Chriscrosser3310 
What y'all think?

**Comment by Chriscrosser3310** [comment]
Sure! It's nice to be consistent

**Comment by TDHTTTT** [comment]
I agree

**Comment by andyyPark** [comment]
Agreed as well

**Comment by omarcostahamido** [comment]
Thanks!
Doing it now.
