### ISSUE TITLE
delete unused branches?

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#6]
I think always creating a branch first for any new addition is a very good practice.
But after it is merged... should it still laying around?

**Comment by andyyPark** [comment]
If that is the common practice then we should delete them! 
I left it there so when we have an issue we can just go and fix from that branch. I am still new to github haha.

**Comment by omarcostahamido** [comment]
you will have to keep updating the branch before creating a new pull
request every time.
I think it is faster to just create a new branch from master and then a
single PR with the updates.

**Comment by omarcostahamido** [comment]
I think I understand that you wanted to have separate branches for every page so that you can work on each independently. That is fine for when we are just adding a new page, but I believe it will soon become a dead weight that constantly needs to be updated, flooding the history with unnecessary commit-PRs. branches `join`, `index`, and `todo` can be deleted now.
As we move forward and want to improve on each page, those improvements might cross reference the work done on other pages, and it will require the constant updates. Also, there is nothing preventing one from creating a branch with the same name of an old deleted branch.

**Comment by omarcostahamido** [comment]
`contact_us` ready for deletion

**Comment by omarcostahamido** [comment]
@andyyPark thanks for cleaning up
