### ISSUE TITLE
adding  a new panel or section: Resources or Articles

### ISSUE THREAD

**Issue by Ahmad-Fermion** [QC-UCI/qc-uci.club#62]
I want to suggest adding a new panel to our website and explain some basic information about quantum computing and other stuff. Explaining a bit about photonic quantum computing and boson sampling. For all topics very briefly. Can you help me with that @andyyPark @omarcostahamido ? I just need a template code and then I or others can contribute.

**Comment by omarcostahamido** [comment]
Hi @Ahmad-Fermion good to hear that.
As I have written elsewhere, a resources page was on the original plan.
@Chriscrosser3310 has created an issue not long ago about it, so, with your added voice to it, I feel we should definitely move forward with it.

For the sake of organization I will ask you to focus the discussion on that issue thread #47 .
(For this reason I'm closing this thread, but we can always access it, and can re-open it, if needed.)

As far as template goes, you can copy one of the html files from another existing page. 
At least that's how I'd go about it. @andyyPark do you have other recommendations?

**Comment by andyyPark** [comment]
yes @omarcostahamido, @Ahmad-Fermion you can just copy one of the existing html files!
