### ISSUE TITLE
rename master branch to main branch

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#65]
title says it all :/
@andyyPark do you agree ?

**Comment by andyyPark** [comment]
Is that the convention? I'm fine with either.

**Comment by omarcostahamido** [comment]
Actually, as of a couple weeks ago, new repositories on created github have `main` branch instead of `master`.
I participate on other github repos where, over the summer, because of all the things that were happening in the country, we did manually change `master` to `main`...

**Comment by omarcostahamido** [comment]
I'm doing it now.

**Comment by omarcostahamido** [comment]
Actually, I just noticed they are working on a way to make the transition more clean and simple:
https://github.com/github/renaming#later-this-year

I'll come back to this at a latter time then.

**Comment by andyyPark** [comment]
@omarcostahamido Ah thats cool. Thanks for letting me know!

**Comment by omarcostahamido** [comment]
>_Beginning in January 2021, we'll begin rolling out functionality to make it easier to rename the default branch of an existing repository_

more soon, then.

**Comment by omarcostahamido** [comment]
I'm ready to make this change, github has made the necessary updates to make a seamless transition.
@andyyPark @TDHTTTT @Ahmad-Fermion if you have forks, or local clones, you might want to give it one last update before I do this. Won't also be that bad if you only update after too. Just wanted to give a heads up first.

**Comment by TDHTTTT** [comment]
Cool! Thanks for the heads up!

**Comment by omarcostahamido** [comment]
Thanks for confirming, @TDHTTTT

**Comment by omarcostahamido** [comment]
DONE
