### ISSUE TITLE
clever greyed out links

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#67]
events page needs greyed out links rules changed for meetings and newsletters tabs.
These need only be greyed out if from previous quarters.

I guess we can already automate it for the whole year based on the reg.uci.edu calendar for [this year](https://reg.uci.edu/calendars/quarterly/2020-2021/quarterly20-21.html), and [next year](https://reg.uci.edu/calendars/quarterly/2021-2022/quarterly21-22.html) already.

Thx

**Comment by andyyPark** [comment]
What about events tab?

**Comment by omarcostahamido** [comment]
I don't think those need to stay ungreyed for the quarter.
Those are more about the future upcoming events really.
