### ISSUE TITLE
add recent newsletters to events>newsletter

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#69]
title says it all.

Need to update deez.

**Comment by andyyPark** [comment]
do you have links to them or are they on notion? I will update them

**Comment by omarcostahamido** [comment]
https://us20.campaign-archive.com/home/?u=9fefbfdf86a0518a32ebcd209&id=40a914ae01

**Comment by omarcostahamido** [comment]
wouldn't it be nice if one could just programmatically populate the newsletter list just by querying the state of [that page](https://us20.campaign-archive.com/home/?u=9fefbfdf86a0518a32ebcd209&id=40a914ae01) instead? Food for thought :)

**Comment by dssikdar** [comment]
temporarily do it manually; something to automate in future

**Comment by omarcostahamido** [comment]
@dssikdar so basically close as NOT completed/ will not fix,  right?

**Comment by omarcostahamido** [comment]
there

**Comment by dssikdar** [comment]
Ok, my bad.
