### ISSUE TITLE
join page

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#7]
- add link to form: https://docs.google.com/forms/d/e/1FAIpQLSdQFlS8dnSIVJz3-ODNYVOm8vjc_BvyazkOISQKMbY-IGMdgg/viewform?usp=sf_link
  - explain that this club registration here is only allowed for ppl at UCI
- add link to slack: 
- add link to linkedin: linkedin.com/company/qc-uci/
- add link to github: https://github.com/QC-UCI/
- add link to subscribe to newsletter:

**Comment by andyyPark** [comment]
Maybe we can close this issue?

**Comment by omarcostahamido** [comment]
my bad. should have done it when merging.

this was fixed by #11
