### ISSUE TITLE
team page

### ISSUE THREAD

**Issue by omarcostahamido** [QC-UCI/qc-uci.club#8]
- current board members
- previous board members
- founding members

**Comment by omarcostahamido** [comment]
@andyyPark heard that you are working on the team page.
If there are any contents from the board members that you'd need and it is not readily available, better start asking for them. It might take a while to collect everything, also because some people are no longer at UCI.

**Comment by andyyPark** [comment]
I was thinking of displaying an image with their names and year. Do you want me to add more info about each member?

**Comment by omarcostahamido** [comment]
Just go with that for now.
Looking forward to starting to see pages emerge.
Once that happens it'll be easier to get help going.

**Comment by andyyPark** [comment]
I just created a PR. Can you take a look? You should be able to view a gif of the team at the bottom of the comment section.

**Comment by omarcostahamido** [comment]
let me see

**Comment by omarcostahamido** [comment]
@andyyPark when it gets time to merge #10 , write this on the merge message:
```
this fixes #8
```

**Comment by andyyPark** [comment]
This was fixed by #10
