### ISSUE TITLE
Tab for projects

### ISSUE THREAD

**Issue by jcwang111** [QC-UCI/qc-uci.club#82]
Tab, like the Events page, detailing the projects we are or have been working on.

**Comment by omarcostahamido** [comment]
Hi there. Thx for opening the issue.
Q1: Do you already have the project information to add?
Q2: do you want to have a go at implementing it?

**Comment by omarcostahamido** [comment]
@dssikdar where exactly was it completed?
It is usually a bad idea to just close things manually as completed without any further reference or explanation... It defeats the purpose of an issue tracker.

**Comment by dssikdar** [comment]
I added the projects.html, which would have our featured project title and summary as description. I have two completed projects and two upcoming ones for the year ahead. 

And sorry for closing without a comment.

**Comment by omarcostahamido** [comment]
When you push a commit, on its description you can add `- this fixes #82` and it will automatically close the referred issue adding a link on the issue to the respective commit. This makes it much easier to keep track of things.

All good. I'm just advocating for good practice, and always learning myself too.
Plus, it is the QC@UCI club. It is nice to see things keep growing well.

Best,
OCH

**Comment by dssikdar** [comment]
Oh okay, I didn’t know that. I’ll use it. Thanks.
