### ISSUE TITLE
Want to put make a sliding/switching picture on the front page

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#86]
It would be nice to create some sort of slideshow of group images. For now, there are side-by-side still images.

**Comment by omarcostahamido** [comment]
Hello @dssikdar 👋
And thank you for using github issues.
Which side by side pictures are you referring to? The 2 on the homepage?
Thank you for trying to give the website a new face. In my opinion, and I'm realizing it now (on vacation accessing on my phone),  it is not very mobile friendly, and that would be a must. Please see #88

**Comment by omarcostahamido** [comment]
For this issue, which deals with re-arraging the front page, please articulate with #83

**Comment by omarcostahamido** [comment]
replying to your continued comment [here](https://github.com/QC-UCI/qc-uci.club/issues/83#issuecomment-1664543927)
> Right now, I have put two pictures below the header. But, it would be nice to create some sort of slide show. In some website I have visited previously, the main image would be changing every 10 seconds and rotating through a list of 4-5 photos.

Do you already have those 4-5 photos? I can take a dab at creating these sliding pictures, if you like to share those.

**Comment by dssikdar** [comment]
I don't have 4-5 photos, but I have three photos. And sure, I can share them here. Thanks for helping :) 

![TimeCrystals](https://github.com/QC-UCI/qc-uci.club/assets/69136009/6c35ee75-8509-4f9a-9cee-d6d99aec12e6)
![GuestSpeaker](https://github.com/QC-UCI/qc-uci.club/assets/69136009/0d01fcfb-20d8-4833-b65c-df1683e28d5f)
![GameDay](https://github.com/QC-UCI/qc-uci.club/assets/69136009/904e9b50-bd71-4e93-b40a-c68419f21080)

**Comment by omarcostahamido** [comment]
thx, let me have a go at it. self assigning.

**Comment by omarcostahamido** [comment]
DONE, create a pr for you to review and merge.

**Comment by dssikdar** [comment]
Really nicely done. Thanks a lot
