### ISSUE TITLE
Updating "Coming Up/Events" page

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#87]
I don't we should have the calendar. And we should update it with planned events.

**Comment by omarcostahamido** [comment]
Sorry, I got confused reading your message. Are you suggesting updating or removing the calendar?

I'm happy someone is finally wanting to address this. And I'm happy to help thinking about it.

Please also refer and address #15 #17 #52 #56

Thank you

**Comment by dssikdar** [comment]
Oh I'm sorry. I wanted to not have the calendar. But I was thinking of having a table with events and the corresponding date only. Does that make more sense?

**Comment by omarcostahamido** [comment]
Thank you for clarifying that.
Yes that does make sense. And it might make it easier to make it mobile friendly.
(Indeed that is what I do on my own [personal page](https://omarcostahamido.com)). Though, I am a Google calendar aficionado and can see how a shared calendar (the original idea) could be a great way to keep everyone in the loop. But the website needs to be cleaner right now, and I'm supportive of this idea ;)

Questions: do you want to keep the previous events listed? You can check what we did in the past to differentiate future and past events/newsletters, if
What is the format like?
Date - time - location - event name ?

Please go ahead with a PR which we can then use to close the pending calendar issues and PR

**Comment by omarcostahamido** [comment]
Also, I just noticed this now from the issue title: are you suggesting to do this on the front page?
my questions regarding format and archive still remain.

**Comment by dssikdar** [comment]
I don't want to keep the previous events listed in the main page. Maybe we can keep in some kind of web archive that isn't visible to club members, but that's optional. I don't know though. What do you think? 

I like the format that you suggested: "Date - time - location - event name"

For your last question, I was originally thinking of putting the upcoming events on the front page. But then, I discarded this idea  because it would probably make the front page too crowded.

**Comment by omarcostahamido** [comment]
> I don't want to keep the previous events listed in the main page. Maybe we can keep in some kind of web archive that isn't visible to club members, but that's optional. I don't know though. What do you think?
I like the format that you suggested: "Date - time - location - event name"

Go ahead. If you'd like me to review before merging you can create a pull request, instead of changing main directly.

> For your last question, I was originally thinking of putting the upcoming events on the front page. But then, I discarded this idea because it would probably make the front page too crowded.

Ok, then the name of the issue should be renamed accordingly:

**Comment by dssikdar** [comment]
I like the way it is right now. We can have the person who manages the website can update events as they come up.
