### ISSUE TITLE
Need to position the elements in a row in the "What we do" section in the front page

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#89]

**Comment by omarcostahamido** [comment]
you mean having them in a row? cause they already seemed centered.

**Comment by dssikdar** [comment]
yes

**Comment by omarcostahamido** [comment]
I can take this one too. And make it mobile friendly, where it will become a column, if portrait.

**Comment by dssikdar** [comment]
Oh, that'll be nice. Thank you.

**Comment by omarcostahamido** [comment]
working on it now

**Comment by omarcostahamido** [comment]
DONE.
please see https://github.com/QC-UCI/qc-uci.club/pull/94

**Comment by dssikdar** [comment]
Thanks so much
