### ISSUE TITLE
Create fixed size of images in slideshow

### ISSUE THREAD

**Issue by dssikdar** [QC-UCI/qc-uci.club#93]
It would be nice to have a fixed size of images (certain height by certain width) so that the "About Us" section does not change position as the slideshow plays through.

**Comment by omarcostahamido** [comment]
Agreed.
If you want I can try that with code, not image editing.
2 options: a) make it scale in terms of height, meaning some images will be
larger others will not use full width.
b) making sure images always use all the available area, and visually
cropping them in height.
What do you think?

**Comment by dssikdar** [comment]
Yes, I would prefer if we didn't edit the images. 

Could you explain option (b) a bit more - as in how it will look?

**Comment by omarcostahamido** [comment]
Option b is basically how it works right now, as in images are scaled based on width, but their height will be cropped to in order to keep the div height constant

**Comment by dssikdar** [comment]
Oh okay. Since I don't want to crop the images based on height, let's go with option a.

**Comment by omarcostahamido** [comment]
DONE
